"""Citation-safe synthesis of research results.

The model only sees numbered, enveloped records and may cite them as [n]. After
generation, citations outside 1..N and identifiers (DOIs/PMIDs) that are not in
the records are stripped, and the reference list is generated by code from the
records themselves — so a citation can never be invented.
"""

from __future__ import annotations

import re

from pydantic import BaseModel, Field

from elara.conversation.i18n import t
from elara.core.errors import ProviderError
from elara.core.logging import get_logger
from elara.providers.base import ChatMessage, CompletionRequest
from elara.providers.service import LLMService
from elara.research.models import Record, ResearchResult
from elara.security.untrusted import SYSTEM_TRUST_POLICY, wrap_untrusted

log = get_logger(__name__)
LANG_NAMES = {"az": "Azerbaijani", "en": "English", "tr": "Turkish"}
_CITE = re.compile(r"\[(\d+(?:\s*[,–-]\s*\d+)*)\]")
_DOI = re.compile(r"\b10\.\d{4,9}/[^\s\]\)>,;]+", re.I)
_PMID = re.compile(r"\bPMID:?\s*(\d{5,9})\b", re.I)


class Synthesis(BaseModel):
    text: str
    used_llm: bool
    removed_citations: list[str] = Field(default_factory=list)


def references_block(result: ResearchResult) -> str:
    return "\n".join(f"[{i}] {r.citation()}" for i, r in enumerate(result.records, 1))


def validate_citations(text: str, n: int, known_ids: set[str]) -> tuple[str, list[str]]:
    removed: list[str] = []

    def fix_cite(m: re.Match) -> str:
        nums = [int(x) for x in re.findall(r"\d+", m.group(1))]
        good = [x for x in nums if 1 <= x <= n]
        removed.extend(f"[{x}]" for x in nums if x not in good)
        return "[" + ", ".join(map(str, good)) + "]" if good else ""

    text = _CITE.sub(fix_cite, text)

    def fix_id(m: re.Match) -> str:
        val = m.group(0).rstrip(".").lower()
        if val in known_ids:
            return m.group(0)
        removed.append(m.group(0))
        return "[unverified identifier removed]"

    text = _DOI.sub(fix_id, text)
    text = _PMID.sub(lambda m: m.group(0) if m.group(1) in known_ids else (
        removed.append(m.group(0)) or "[unverified identifier removed]"), text)
    return re.sub(r"[ \t]{2,}", " ", text).strip(), removed


SOURCE_LABELS = {"pubmed": "PubMed", "europepmc": "Europe PMC", "crossref": "Crossref",
                 "semantic_scholar": "Semantic Scholar", "clinvar": "ClinVar",
                 "ncbi_gene": "NCBI Gene", "ensembl": "Ensembl", "gnomad": "gnomAD"}


def label(source: str) -> str:
    return SOURCE_LABELS.get(source, source)


def record_line(i: int, r: Record) -> str:
    parts = [f"{i}. {r.title.rstrip('.')}."]
    venue_year = ", ".join(str(x) for x in (r.venue, r.year) if x)
    if venue_year:
        parts.append(venue_year + ".")
    ids = []
    if r.pmid:
        ids.append(f"PMID: {r.pmid}")
    if r.doi:
        ids.append(f"DOI: {r.doi}")
    if r.evidence_type.value != "unknown":
        ids.append(r.evidence_type.value.replace("_", " "))
    if ids:
        parts.append("[" + "; ".join(ids) + "]")
    if url := r.best_url():
        parts.append(url)
    return " ".join(parts)


def _reason(kind: str | None, language: str) -> str:
    key = f"reason_{kind}" if kind in ("unreachable", "rate_limited", "timeout",
                                       "blocked") else "reason_other"
    return t(key, language)


def source_listing(result: ResearchResult, language: str,
                   fallback: ResearchResult | None = None) -> str:
    """Deterministic, source-faithful listing for explicitly requested sources (no LLM).

    Records keep the order the source returned; identifiers are shown only when the
    source supplied them; failures are stated, and any fallback is labelled as such.
    """
    lines: list[str] = []
    query = result.plan.query
    by_source: dict[str, list[Record]] = {}
    for r in result.records:
        by_source.setdefault(r.source, []).append(r)
    for o in result.outcomes:
        name = label(o.source)
        if not o.ok:
            lines.append(t("research_source_unavailable", language, source=name,
                           reason=_reason(o.error_kind, language), error=o.error or "?"))
        elif not by_source.get(o.source):
            lines.append(t("research_source_empty", language, source=name, query=query))
        else:
            cached = t("cached_note", language) if o.cached else ""
            lines.append(t("research_source_header", language, source=name, query=query,
                           cached=cached))
            lines += [record_line(i, r) for i, r in enumerate(by_source[o.source], 1)]
        lines.append("")
    if fallback is not None and fallback.records:
        requested = ", ".join(label(o.source) for o in result.outcomes)
        used = ", ".join(sorted({label(r.source) for r in fallback.records}))
        lines.append(t("research_fallback_header", language, sources=used, requested=requested))
        lines += [record_line(i, r) + f" ({label(r.source)})"
                  for i, r in enumerate(fallback.records, 1)]
    return "\n".join(lines).strip()


class Synthesizer:
    def __init__(self, llm: LLMService | None):
        self.llm = llm

    async def synthesize(self, question: str, result: ResearchResult, language: str) -> Synthesis:
        if not result.records and result.outcomes and not any(o.ok for o in result.outcomes):
            return Synthesis(text=t("research_all_failed", language,
                                    sources=", ".join(result.failed_sources)), used_llm=False)
        if not result.records:
            text = t("research_none", language, query=result.plan.original)
            if result.failed_sources:
                text += "\n" + t("research_failed_sources", language,
                                 sources=", ".join(result.failed_sources))
            return Synthesis(text=text, used_llm=False)
        if self.llm and self.llm.available:
            try:
                return await self._llm(question, result, language)
            except ProviderError as e:
                log.warning("research.synthesis_llm_failed", extra={"error": str(e)})
        return self._fallback(result, language)

    async def _llm(self, question: str, result: ResearchResult, language: str) -> Synthesis:
        blocks = []
        for i, r in enumerate(result.records, 1):
            meta = (f"[{i}] {r.title}\nType: {r.evidence_type.value}; Source: {r.source}"
                    f"{'; also in ' + ', '.join(r.also_in) if r.also_in else ''}; "
                    f"Year: {r.year or 'n/a'}; Venue: {r.venue or 'n/a'}")
            body = (r.abstract or "(no abstract available)")[:1500]
            blocks.append(meta + "\n" + body)
        wrapped = wrap_untrusted("\n\n".join(blocks), f"research:{result.plan.query}",
                                 max_chars=30_000)
        system = (
            "You are ELARA's research synthesizer. Answer the user's question using ONLY the "
            "numbered sources provided. Cite sources inline as [n]. Never invent sources, "
            "numbers, DOIs or PMIDs. If the sources do not answer the question, say so plainly. "
            "Point out evidence type where it matters (review vs primary research vs preprint "
            "(not peer-reviewed) vs database record). Be concise: a short synthesis, then key "
            "points. Do not add a reference list; it is appended automatically. "
            f"Write in {LANG_NAMES.get(language, 'English')}.\n\n{SYSTEM_TRUST_POLICY}")
        msg = f"Question: {question}\n\nSources:\n{wrapped.text}"
        resp = await self.llm.complete(CompletionRequest(
            system=system, messages=[ChatMessage(role="user", text=msg)], max_tokens=1500),
            tier="strong", purpose="research_synthesis")
        known = {r.doi.lower() for r in result.records if r.doi} | {
            r.pmid for r in result.records if r.pmid}
        body, removed = validate_citations(resp.text, len(result.records), known)
        if removed:
            log.warning("research.citations_removed", extra={"removed": removed[:10]})
        text = body + "\n\n" + references_block(result)
        if result.failed_sources:
            text += "\n\n" + t("research_failed_sources", language,
                               sources=", ".join(result.failed_sources))
        return Synthesis(text=text, used_llm=True, removed_citations=removed)

    @staticmethod
    def _fallback(result: ResearchResult, language: str) -> Synthesis:
        lines = [t("research_header", language, query=result.plan.original), "",
                 references_block(result)]
        if result.failed_sources:
            lines += ["", t("research_failed_sources", language,
                            sources=", ".join(result.failed_sources))]
        lines += ["", t("research_no_llm_note", language)]
        return Synthesis(text="\n".join(lines), used_llm=False)
